apisix:
  enable_admin: false
  ssl:
    ssl_trusted_certificate: /usr/local/cloud/cert/ca.crt

etcd:
  host:
    - "https://xx:443"
  tls:
    cert: /usr/local/cloud/cert/tls.crt
    key: /usr/local/cloud/cert/tls.key
    sni: xx
    verify: true

plugin_attr:
  cloud:
    domain: xx
    port: 443
    cert: /usr/local/cloud/cert/tls.crt
    key: /usr/local/cloud/cert/tls.key

